name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure a full clone for better analysis

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Install Dependencies
        run: npm install  # Modify this based on your project needs

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # ğŸ› ï¸ Install Docker Scout
      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
          echo "$HOME/.docker/cli-plugins" >> $GITHUB_PATH
          chmod +x $HOME/.docker/cli-plugins/docker-scout
        shell: bash

      # ğŸ” Run Docker Scout Scan
      - name: Run Docker Scout Scan
        run: |
          $HOME/.docker/cli-plugins/docker-scout quickview fs://.
          $HOME/.docker/cli-plugins/docker-scout cves fs://.

     # ğŸ—ï¸ Build and Push Docker Image
      - name: Docker Build and Push
        run: |
          docker build -t sevenajay/myntra:latest .
          docker tag sevenajay/myntra:latest hitanshidarji/myntra-app:latest
          docker push hitanshidarji/myntra-app:latest
        env:
          DOCKER_CLI_ACI: 1


      # ğŸ›¡ï¸ Docker Scout Scan on Image
      - name: Docker Scout Image Scan
        run: |
          $HOME/.docker/cli-plugins/docker-scout quickview hitanshidarji/myntra-app:latest
          $HOME/.docker/cli-plugins/docker-scout cves hitanshidarji/myntra-app:latest

        deploy:
         needs: build-analyze-scan
         runs-on: self-hosted # Use your self-hosted runner label here  
         
      - name: Run the container
        run: docker run -d --name myntra -p 3000:3000 sevenajay/myntra:latest
